services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "Benoit"
      PASSWORD: "Yaknowme123"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
      DISK_SIZE: "700G"
      REGION: "fr-BE"
      KEYBOARD: "fr-FR"
      LANGUAGE: "French"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
